development:
  adapter: postgresql
  encoding: unicode
  database: wishez_development
  pool: 5
  host: localhost
  username: postgres
  password: wdi2

production:
  adapter: postgresql
  encoding: unicode
  database: wishez_production
  pool: 5
  host: localhost
  username: postgres
  password: wdi2


